/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg2109106078_rian.syaputra.ainun.naim_tugas_pbo;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static pkg2109106078_rian.syaputra.ainun.naim_tugas_pbo.Login.nama;

/**
 *
 * @author LENOVO
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() throws SQLException{
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CpassField = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        passField = new javax.swing.JPasswordField();
        JButton_Register = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Jbutton_Sign_In = new javax.swing.JButton();
        warnTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(370, 480));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(100, 92, 170));
        jPanel1.setMinimumSize(new java.awt.Dimension(360, 40));
        jPanel1.setPreferredSize(new java.awt.Dimension(360, 40));

        jLabel8.setFont(new java.awt.Font("Futura Bk BT", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("REGISTER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 360, 40);

        jPanel2.setBackground(new java.awt.Color(45, 46, 55));
        jPanel2.setMinimumSize(new java.awt.Dimension(360, 440));
        jPanel2.setPreferredSize(new java.awt.Dimension(360, 440));

        jLabel1.setFont(new java.awt.Font("Futura Bk BT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 171, 225));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pelanggan Baru!");

        jLabel2.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(84, 186, 185));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sudah punya akun?");

        jLabel3.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 171, 225));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Password");

        userTxt.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 171, 225));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Username");

        CpassField.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 171, 225));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Confirm Password");

        passField.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N

        JButton_Register.setBackground(new java.awt.Color(41, 52, 98));
        JButton_Register.setForeground(new java.awt.Color(84, 186, 185));
        JButton_Register.setText("REGISTER");
        JButton_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_RegisterActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(84, 186, 185));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Masukkan Identitas Anda");

        Jbutton_Sign_In.setBackground(new java.awt.Color(41, 52, 98));
        Jbutton_Sign_In.setForeground(new java.awt.Color(84, 186, 185));
        Jbutton_Sign_In.setText("SIGN IN");
        Jbutton_Sign_In.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbutton_Sign_InActionPerformed(evt);
            }
        });

        warnTxt.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        warnTxt.setForeground(new java.awt.Color(84, 186, 185));
        warnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JButton_Register)
                .addGap(138, 138, 138))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(userTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CpassField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(passField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(warnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Jbutton_Sign_In)
                .addGap(143, 143, 143))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(83, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(71, 71, 71)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CpassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JButton_Register)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jbutton_Sign_In)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(88, 88, 88)
                    .addComponent(jLabel7)
                    .addContainerGap(334, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 40, 360, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButton_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_RegisterActionPerformed
        // TODO add your handling code here:
        if (CpassField.getText().equals(passField.getText())){
                String username = userTxt.getText();
                String password = passField.getText();
                
                //boolean registerSuccess = User.register(username, password);
                try {
                    Connection conn;
                    conn = koneksi.getKoneksi();
                    String sql = "SELECT * FROM tb_user WHERE username = ?";
                    PreparedStatement statement = conn.prepareStatement(sql);
                    statement.setString(1, username);
                    ResultSet result = statement.executeQuery();
                    if (result.next()) {
                        warnTxt.setText( "Username sudah ada!");
                        return;    
                    }
                    //else {
                    String query = "INSERT INTO tb_user (username, password, level) VALUES (?, ?, ?)";
                    PreparedStatement statement2 = conn.prepareStatement(query);
                    statement2.setString(1, username);
                    statement2.setString(2, password);
                    statement2.setString(3, "user");
                    int rowsAffected = statement2.executeUpdate();
                    //return rowsAffected > 0;
                    if (rowsAffected > 0) {
                        Login lg = new Login();
                        lg.setVisible(true);
                        lg.pack();
                        lg.setLocationRelativeTo(null);
                        this.setVisible(false);
                        lg.setDefaultCloseOperation(Register.EXIT_ON_CLOSE);
                    } 
                    else {
                        warnTxt.setText( "Registrasi gagal");
                    }
                    //}
                } catch (SQLException e) {
                    e.printStackTrace();
                }
        }
        else {
                 warnTxt.setText("Password yang dimasukkan tidak sama!");
        }
            
    }//GEN-LAST:event_JButton_RegisterActionPerformed

    private void Jbutton_Sign_InActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbutton_Sign_InActionPerformed
        // TODO add your handling code here:
        Login lg = null;
        try {
            lg = new Login();
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
                 lg.setVisible(true);
                 lg.pack();
                 lg.setLocationRelativeTo(null);
                 this.setVisible(false);
                 lg.setDefaultCloseOperation(Login.EXIT_ON_CLOSE);
    }//GEN-LAST:event_Jbutton_Sign_InActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Register().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CpassField;
    private javax.swing.JButton JButton_Register;
    private javax.swing.JButton Jbutton_Sign_In;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField passField;
    private javax.swing.JTextField userTxt;
    private javax.swing.JLabel warnTxt;
    // End of variables declaration//GEN-END:variables
}
